package constants

var (
	SCREEN_WIDTH  = 640
	SCREEN_HEIGHT = 480
	CELL_SIZE = 32
	CENTER_AGENT = 0.5
	
	NB_AGENTS = 30

	INCREMENTAL_VELOCITY = 0.005
	INCREMENTAL_DIRECTION = 0.05
	MIN_VELOCITY = 0.1
	MAX_VELOCITY = 1.0
	CLOSE_TO_TARGET = 0.05
	SLOW_VELOCITY_THRESHOLD = 0.3
	LOW_DISTANCE = 5.0
	
	VISION_RANGE = 3.0
	
	TIC_DURATION = 30
)
