package constants

var (
	SCREEN_WIDTH   = 640
	SCREEN_HEIGHT  = 480
	CELL_SIZE      = 32
	HALF_CELL_SIZE = float64(CELL_SIZE / 2)
	CENTER_AGENT   = 0.5

	CLOSE_TO_TARGET         = 0.05
	SLOW_VELOCITY_THRESHOLD = 0.3
	LOW_DISTANCE            = 5.0

	VISION_RANGE = 10.0

	MAX_BATTERY = 100.0

	AGENT_CLOSE_DISTANCE = 0.1
	AGENT_REGENERATION_RANDOM_POS_DISTANCE = 1.5
	RECALC_DISTANCE = 5.0
)
