// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package drone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionMove-0]
	_ = x[ActionPick-1]
	_ = x[ActionDeliver-2]
}

const _ActionType_name = "ActionMoveActionPickActionDeliver"

var _ActionType_index = [...]uint8{0, 10, 20, 33}

func (i ActionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionType_index)-1 {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[idx]:_ActionType_index[idx+1]]
}
