// Code generated by "stringer -type=AgentState"; DO NOT EDIT.

package drone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateFindingMission-0]
	_ = x[StateWandering-1]
	_ = x[StateMovingToDelivery-2]
	_ = x[StateMovingToRecharge-3]
	_ = x[StateMovingToDestination-4]
	_ = x[StateGrabbing-5]
	_ = x[StateDelivering-6]
	_ = x[StateRecharging-7]
}

const _AgentState_name = "StateFindingMissionStateWanderingStateMovingToDeliveryStateMovingToRechargeStateMovingToDestinationStateGrabbingStateDeliveringStateRecharging"

var _AgentState_index = [...]uint8{0, 19, 33, 54, 75, 99, 112, 127, 142}

func (i AgentState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AgentState_index)-1 {
		return "AgentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AgentState_name[_AgentState_index[idx]:_AgentState_index[idx+1]]
}
