// Code generated by "stringer -type=AgentState"; DO NOT EDIT.

package drone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateWandering-0]
	_ = x[StateMovingToDelivery-1]
	_ = x[StateMovingToRecharge-2]
	_ = x[StateMovingToDestination-3]
	_ = x[StateGrabbing-4]
	_ = x[StateDelivering-5]
	_ = x[StateRecharging-6]
}

const _AgentState_name = "StateWanderingStateMovingToDeliveryStateMovingToRechargeStateMovingToDestinationStateGrabbingStateDeliveringStateRecharging"

var _AgentState_index = [...]uint8{0, 14, 35, 56, 80, 93, 108, 123}

func (i AgentState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AgentState_index)-1 {
		return "AgentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AgentState_name[_AgentState_index[idx]:_AgentState_index[idx+1]]
}
